In [2]:
import pandas as pd

In [3]:
a=pd.read_csv(r"C:\Users\subhadip sinha\OneDrive\CODING\PYTHON\Scikit-Learn\5.ONE HOT ENCODING\aa.csv")
a

                Car_Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5  69000.0        18000.0       6.0
1                  BMW X5  35000.0            NaN       3.0
2                  BMW X5      NaN        26100.0       5.0
3                  BMW X5  22500.0            NaN       NaN
4                  BMW X5  46000.0        31500.0       4.0
5                 Audi A5  59000.0        29400.0       5.0
6                 Audi A5  52000.0        32000.0       5.0
7                 Audi A5      NaN        19300.0       6.0
8                 Audi A5  91000.0        12000.0       NaN
9   Mercedez Benz C class      NaN        22000.0       6.0
10  Mercedez Benz C class  83000.0        20000.0       7.0
11  Mercedez Benz C class  79000.0        21000.0       7.0
12  Mercedez Benz C class      NaN        33000.0       5.0
13                 BMW X5      NaN            NaN       6.0
14                    BMW    350.0          340.0       2.0
15                    BMW  57000.0        26100.0       NaN
16                   BMW5   2250.0          400.0       NaN
17                 BMW X5     46.0        31500.0       4.0
18                    NaN  59000.0           29.0       5.0
19                Audi A5  52000.0        32000.0       5.0
20                Audi A5      NaN        19300.0       NaN
21                    NaN  91000.0        12000.0       NaN

In [5]:
pd.get_dummies(a,drop_first=True)

,Mileage,Sell Price($),Age(yrs),Car_Model_BMW,Car_Model_BMW X5,Car_Model_BMW5,Car_Model_Mercedez Benz C class
0,69000.0,18000.0,6.0,False,True,False,False
1,35000.0,NaN,3.0,False,True,False,False
2,NaN,26100.0,5.0,False,True,False,False
3,22500.0,NaN,NaN,False,True,False,False
4,46000.0,31500.0,4.0,False,True,False,False
5,59000.0,29400.0,5.0,False,False,False,False
6,52000.0,32000.0,5.0,False,False,False,False
7,NaN,19300.0,6.0,False,False,False,False
8,91000.0,12000.0,NaN,False,False,False,False
9,NaN,22000.0,6.0,False,False,False,True
10,83000.0,20000.0,7.0,False,False,False,True
11,79000.0,21000.0,7.0,False,False,False,True
12,NaN,33000.0,5.0,False,False,False,True
13,NaN,NaN,6.0,False,True,False,False
14,350.0,340.0,2.0,True,False,False,False
15,57000.0,26100.0,NaN,True,False,False,False
16,2250.0,400.0,NaN,False,False,True,False
17,46.0,31500.0,4.0,False,True,False,False
18,59000.0,29.0,5.0,False,False,False,False
19,52000.0,32000.0,5.0,False,False,False,False
20,NaN,19300.0,NaN,False,False,False,False
21,91000.0,12000.0,NaN,False,False,False,False